import { AdminEmptyState, AdminMasthead } from '@/Components/Admin/AdminSurface';
import AppIcon from '@/Components/AppIcon';
import Link from '@/Components/PrefetchLink';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { getSportArtwork } from '@/Support/sportArtwork';
import { adminStyles } from '@/Support/adminStyles';
import React from 'react';
import { Head, useForm, usePage } from '@inertiajs/react';
import { useEffect, useMemo, useState } from 'react';

const field = `mt-1 ${adminStyles.field}`;
const primary = adminStyles.primaryAction;
const quiet = adminStyles.secondaryAction;

function sportWorkspaceUrl(eventId, sportId, divisionId = null) {
    const base = route('admin.sports.show', [eventId, sportId]);
    return divisionId ? `${base}?division=${encodeURIComponent(divisionId)}` : base;
}

function CreateSportModal({ event, onClose }) {
    const form = useForm({ name: '', slug: '', division_name: '' });
    const submit = (eventObject) => {
        eventObject.preventDefault();
        form.post(route('admin.sports.store', event.id), { preserveScroll: true, onSuccess: onClose });
    };
    return <div className="fixed inset-0 z-50"><button type="button" aria-label="Close add sport backdrop" onClick={onClose} className="absolute inset-0 bg-foreground/45" /><div role="dialog" aria-modal="true" aria-labelledby="create-sport-title" className="absolute left-1/2 top-1/2 w-[min(32rem,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 border border-border bg-surface p-6 text-foreground shadow-[0_12px_32px_rgb(0_26_63/0.14)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">New sport</p><h2 id="create-sport-title" className="mt-1 text-2xl font-bold">Add a sport and division</h2></div><button type="button" autoFocus onClick={onClose} aria-label="Close add sport" className="grid size-11 place-items-center rounded-sm"><AppIcon name="close" /></button></div><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-xs font-bold uppercase">Sport name<input required value={form.data.name} onChange={(eventObject) => form.setData('name', eventObject.target.value)} className={field} /></label><label className="block text-xs font-bold uppercase">First division<input required value={form.data.division_name} onChange={(eventObject) => form.setData('division_name', eventObject.target.value)} className={field} /></label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={quiet}>Cancel</button><button type="submit" disabled={event.archived || form.processing} className={primary}><AppIcon name="plus" />Create sport</button></div></form></div></div>;
}

function SportCard({ event, sport, onSettings }) {
    const fallback = getSportArtwork(sport.name);
    const cover = sport.cover?.url ? sport.cover : fallback;
    const attention = sport.attention?.kind === 'cover' && fallback ? { ...sport.attention, kind: 'none', label: 'Curated image ready' } : sport.attention;
    return <article className={`overflow-hidden border bg-surface transition-colors hover:border-primary ${sport.active ? 'border-border' : 'border-border opacity-75'}`}><div className="relative h-44 overflow-hidden bg-foreground">{cover?.url ? <img src={cover.url} alt={cover.alt || `${sport.name} sport cover`} className="h-full w-full object-cover" /> : null}<div className="absolute inset-x-0 bottom-0 bg-foreground/85 px-5 py-3"><p className="text-[0.62rem] font-bold uppercase tracking-[0.15em] text-accent">Event sport</p><h2 className="mt-1 text-3xl font-bold text-white">{sport.name}</h2></div></div><div className="p-5"><div className="flex items-start justify-between gap-4"><p className="text-sm text-muted">{sport.division_count} active division{sport.division_count === 1 ? '' : 's'} / {sport.player_count} players</p><span className={`rounded-full px-2 py-1 text-[0.62rem] font-bold uppercase ${sport.active ? 'bg-primary/10 text-primary' : 'bg-surface-muted text-muted'}`}>{sport.active ? 'Active' : 'Inactive'}</span></div><dl className="mt-4 grid grid-cols-2 gap-4 border-y border-border py-4 text-sm"><div><dt className="text-[0.62rem] uppercase tracking-[0.08em] text-muted">Rosters</dt><dd className="mt-1 font-semibold">{sport.locked_entries}/{sport.counts.entries} approved</dd></div><div><dt className="text-[0.62rem] uppercase tracking-[0.08em] text-muted">Next activity</dt><dd className="mt-1 truncate font-semibold">{sport.next_activity?.title ?? 'Not scheduled'}</dd></div><div><dt className="text-[0.62rem] uppercase tracking-[0.08em] text-muted">Visibility</dt><dd className="mt-1 font-semibold">{sport.next_activity ? sport.next_activity.public ? 'Public schedule' : 'Draft schedule' : 'Not scheduled'}</dd></div><div><dt className="text-[0.62rem] uppercase tracking-[0.08em] text-muted">Attention</dt><dd className={`mt-1 font-semibold ${attention?.kind === 'none' ? 'text-primary' : 'text-accent-foreground'}`}>{attention?.label ?? 'No issues'}</dd></div></dl><div className="mt-4 flex gap-2"><Link href={sportWorkspaceUrl(event.id, sport.id)} className={`${primary} flex-1`}>Open sport hub <AppIcon name="arrow-right" className="size-4" /></Link><button type="button" onClick={onSettings} aria-label={`Open ${sport.name} settings`} className="grid size-11 shrink-0 place-items-center rounded-sm border border-border text-primary hover:border-primary"><AppIcon name="settings" className="size-4" /></button></div></div></article>;
}

export default function Index({ event, sports = [] }) {
    const [selected, setSelected] = useState(null);
    const [createOpen, setCreateOpen] = useState(false);
    const [query, setQuery] = useState('');
    const { flash, errors } = usePage().props;
    const visibleSports = useMemo(() => sports.filter((sport) => sport.name.toLowerCase().includes(query.trim().toLowerCase())), [sports, query]);
    const selectedSport = selected ? sports.find((sport) => String(sport.id) === String(selected.id)) || selected : null;

    return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{event.name}</p><h1 className="text-2xl font-bold">Sports Directory</h1></div>}><Head title="Sports Directory" /><main className={adminStyles.page}><div className="mx-auto max-w-[96rem] space-y-6">{flash?.status ? <div role="status" className="border border-primary/35 bg-primary/10 p-4 text-sm">{flash.status}</div> : null}{Object.keys(errors || {}).length ? <div role="alert" className="border border-danger/35 bg-danger-surface p-4 text-sm text-danger">{Object.values(errors).join(' ')}</div> : null}<AdminMasthead eyebrow="Competition operations" title="Every sport, one clear workspace" description="Open a sport hub to choose a division, then go straight to the work in front of you." actions={<><Link href={route('admin.sports.schedules', event.id)} className={adminStyles.secondaryAction}><AppIcon name="calendar" className="size-4" />Event schedule</Link><button type="button" onClick={() => setCreateOpen(true)} className={adminStyles.primaryAction}><AppIcon name="plus" />Add sport</button></>} /><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold text-foreground">Sports directory</h2><p className="mt-1 text-sm text-muted">Choose a sport hub, then make one clear next choice.</p></div><label className="relative w-full sm:max-w-sm"><span className="sr-only">Search sports</span><AppIcon name="search" className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted" /><input type="search" value={query} onChange={(eventObject) => setQuery(eventObject.target.value)} placeholder="Find a sport" className={`${adminStyles.field} pl-10`} /></label></div>{visibleSports.length ? <section className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3" aria-label="Event sports">{visibleSports.map((sport) => <SportCard key={sport.id} event={event} sport={sport} onSettings={() => setSelected(sport)} />)}</section> : <AdminEmptyState title={sports.length ? 'No sports match that search' : 'No sports configured'} description={sports.length ? 'Try a different sport name.' : 'Add the first sport and division to start the event workspace.'} />}</div></main>{selectedSport ? <SportDrawer event={event} sport={selectedSport} onClose={() => setSelected(null)} /> : null}{createOpen ? <CreateSportModal event={event} onClose={() => setCreateOpen(false)} /> : null}</AuthenticatedLayout>;
}

function SportDrawer({ event, sport, onClose }) {
    const details = useForm({ name: sport.name, slug: sport.slug });
    const division = useForm({ name: '', slug: '' });
    const state = useForm({ active: !sport.active, reason: '' });
    const cover = useForm({ cover: null, alt_text: sport.draft_cover?.alt_text || sport.published_cover?.alt_text || '' });
    const publishForm = useForm({});
    const withdrawForm = useForm({ reason: '' });

    useEffect(() => {
        const handler = (eventObject) => { if (eventObject.key === 'Escape') onClose(); };
        document.addEventListener('keydown', handler);
        return () => document.removeEventListener('keydown', handler);
    }, [onClose]);

    useEffect(() => {
        cover.setData('alt_text', sport.draft_cover?.alt_text || sport.published_cover?.alt_text || '');
    }, [sport.id, sport.draft_cover?.id, sport.published_cover?.id]);

    const uploadCover = (eventObject) => {
        eventObject.preventDefault();
        cover.post(route('admin.cover-images.store', [event.id, sport.id]), { forceFormData: true, preserveScroll: true, onSuccess: () => cover.reset('cover') });
    };
    const publishDraft = () => publishForm.post(route('admin.cover-images.publish', [event.id, sport.draft_cover.id]), { preserveScroll: true });
    const withdrawPublished = (eventObject) => {
        eventObject.preventDefault();
        withdrawForm.post(route('admin.cover-images.withdraw', [event.id, sport.published_cover.id]), { preserveScroll: true, onSuccess: () => withdrawForm.reset() });
    };

    return <div className="fixed inset-0 z-50"><button type="button" aria-label="Close sport settings backdrop" onClick={onClose} className="absolute inset-0 bg-foreground/45" /><aside role="dialog" aria-modal="true" aria-labelledby="sport-settings-title" className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto border-l border-border bg-background shadow-[0_0_24px_rgb(0_26_63/0.12)]">
        <header className="sticky top-0 z-10 flex items-start justify-between border-b border-border bg-surface p-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Sport settings</p><h2 id="sport-settings-title" className="mt-1 text-2xl font-bold">{sport.name}</h2></div><button type="button" autoFocus onClick={onClose} aria-label="Close sport settings" className="grid size-11 place-items-center rounded-sm focus-visible:ring-2 focus-visible:ring-ring"><AppIcon name="close" /></button></header>
        <div className="space-y-5 p-5">
            <section className="rounded-sm border border-border bg-surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-accent-foreground">Public presentation</p><h3 className="mt-1 text-lg font-bold">Sport cover image</h3><p className="mt-2 text-sm leading-6 text-muted">Upload a private draft, preview it here, then publish only when the image and description are ready.</p></div><AppIcon name="overview" className="size-5 text-primary" /></div>
                <form onSubmit={uploadCover} className="mt-4 space-y-3 border-t border-border pt-4"><label className="block text-xs font-bold uppercase">New cover<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={(eventObject) => cover.setData('cover', eventObject.target.files?.[0] || null)} className={`${field} file:mr-3 file:rounded-md file:border-0 file:bg-primary/10 file:px-3 file:py-2 file:text-xs file:font-bold file:text-primary`} /></label><p className="text-xs text-muted">JPG, PNG, or WebP. Minimum 800 x 450, maximum 5 MB.</p><label className="block text-xs font-bold uppercase">Image description<textarea required minLength={10} maxLength={180} value={cover.data.alt_text} onChange={(eventObject) => cover.setData('alt_text', eventObject.target.value)} className={field} placeholder="Describe the sport and venue shown" /></label><button type="submit" disabled={event.archived || cover.processing || !cover.data.cover} className={primary}>{cover.processing ? 'Uploading...' : 'Upload private draft'}</button>{cover.errors.cover ? <p className="text-sm text-danger">{cover.errors.cover}</p> : null}{cover.errors.alt_text ? <p className="text-sm text-danger">{cover.errors.alt_text}</p> : null}</form>
                {sport.draft_cover ? <div className="mt-5 rounded-sm border border-accent/50 bg-accent/10 p-3"><div className="flex gap-3"><img src={sport.draft_cover.preview_url} alt={sport.draft_cover.alt_text} className="h-20 w-32 rounded-md object-cover" /><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.1em] text-accent-foreground">Private draft r{sport.draft_cover.revision}</p><p className="mt-1 text-sm font-semibold text-foreground">{sport.draft_cover.alt_text}</p><button type="button" onClick={publishDraft} disabled={event.archived || publishForm.processing} className={`${primary} mt-3 min-h-9 px-3 text-xs`}>{publishForm.processing ? 'Publishing...' : 'Publish draft'}</button></div></div></div> : null}
                {sport.published_cover ? <div className="mt-4 rounded-sm border border-border p-3"><div className="flex gap-3">{sport.published_cover.public_url ? <img src={sport.published_cover.public_url} alt={sport.published_cover.alt_text} className="h-20 w-32 rounded-md object-cover" /> : null}<div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.1em] text-primary">Published image</p><p className="mt-1 text-sm font-semibold text-foreground">{sport.published_cover.alt_text}</p></div></div><form onSubmit={withdrawPublished} className="mt-3 border-t border-border pt-3"><label className="block text-xs font-bold uppercase">Withdrawal reason<textarea required minLength={5} value={withdrawForm.data.reason} onChange={(eventObject) => withdrawForm.setData('reason', eventObject.target.value)} className={field} placeholder="Why should this public image be removed?" /></label><button type="submit" disabled={event.archived || withdrawForm.processing} className="mt-3 inline-flex min-h-9 items-center justify-center rounded-sm border border-danger/40 px-3 text-xs font-bold text-danger hover:bg-danger/10">{withdrawForm.processing ? 'Withdrawing...' : 'Withdraw public image'}</button></form></div> : null}
            </section>
            <form onSubmit={(eventObject) => { eventObject.preventDefault(); details.patch(route('admin.sports.update', [event.id, sport.id]), { preserveScroll: true }); }} className="rounded-sm border border-border bg-surface p-5"><h3 className="text-lg font-bold">Identity</h3><label className="mt-4 block text-xs font-bold uppercase">Name<input disabled={event.archived} value={details.data.name} onChange={(eventObject) => details.setData('name', eventObject.target.value)} className={field} /></label><label className="mt-3 block text-xs font-bold uppercase">Public slug<input disabled={event.archived || sport.has_history} value={details.data.slug} onChange={(eventObject) => details.setData('slug', eventObject.target.value)} className={field} /></label>{sport.has_history ? <p className="mt-2 text-xs text-muted">Slug locked because contest history exists.</p> : null}<button type="submit" disabled={event.archived || details.processing} className={`mt-4 ${primary}`}><AppIcon name="check" />Save changes</button></form>
            <form onSubmit={(eventObject) => { eventObject.preventDefault(); state.patch(route('admin.sports.state', [event.id, sport.id]), { preserveScroll: true }); }} className="rounded-sm border border-border bg-surface p-5"><h3 className="text-lg font-bold">Availability</h3><p className="mt-2 text-sm text-muted">Deactivation preserves history and removes this sport from new entries, assignments, schedules, and the public directory.</p>{sport.active ? <label className="mt-4 block text-xs font-bold uppercase">Required reason<textarea required value={state.data.reason} onChange={(eventObject) => state.setData('reason', eventObject.target.value)} className={field} /></label> : <p className="mt-3 text-sm text-accent-foreground">Reason: {sport.deactivation_reason}</p>}<button type="submit" disabled={event.archived || state.processing} className={`mt-4 ${primary} ${sport.active ? '!bg-accent !text-accent-foreground' : '!bg-primary'}`}><AppIcon name={sport.active ? 'pause' : 'play'} />{sport.active ? 'Deactivate sport' : 'Reactivate sport'}</button></form>
            <section className="rounded-sm border border-border bg-surface p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Divisions</h3><p className="mt-1 text-sm text-muted">Open a division when you need roster, bracket, schedule, or result detail.</p></div><Link href={sportWorkspaceUrl(event.id, sport.id)} className="text-xs font-bold text-primary underline">Open hub</Link></div><div className="mt-4 space-y-3">{sport.divisions.map((item) => <div key={item.id} className="rounded-sm border border-border p-4"><div className="flex justify-between gap-4"><div><strong>{item.name}</strong><p className="mt-1 text-xs capitalize text-muted">{item.format?.replaceAll('_', ' ') ?? 'Format not set'} / {item.participant_mode ?? 'mode not set'} / {item.rule_state}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[0.65rem] font-bold uppercase ${item.active ? 'bg-primary/10 text-primary' : 'bg-surface-muted text-muted'}`}>{item.active ? 'Active' : 'Inactive'}</span></div><p className="mt-2 text-xs text-muted">Roster {item.roster_min ?? 'not set'} - {item.roster_max ?? 'not set'} / {item.schedule_published ? 'Schedule public' : 'Schedule private'}</p>{item.blockers.length ? <p className="mt-2 text-xs text-accent-foreground">{item.blockers.join(' ')}</p> : null}<div className="mt-3 flex flex-wrap gap-3"><Link className="text-xs font-bold text-primary underline" href={route('admin.departments.index', event.id)}>Teams</Link><Link className="text-xs font-bold text-primary underline" href={route('admin.sports.tournament', [event.id, item.id])}>Bracket</Link><Link className="text-xs font-bold text-primary underline" href={route('admin.sports.schedules', { event: event.id, competition: sport.id, division: item.id })}>Schedule</Link></div></div>)}</div><form onSubmit={(eventObject) => { eventObject.preventDefault(); division.post(route('admin.sports.divisions.store', [event.id, sport.id]), { preserveScroll: true, onSuccess: () => division.reset() }); }} className="mt-5 border-t border-border pt-4"><label className="text-xs font-bold uppercase">New division<input required disabled={event.archived} value={division.data.name} onChange={(eventObject) => division.setData('name', eventObject.target.value)} className={field} /></label><button type="submit" disabled={event.archived || division.processing} className={`mt-3 ${primary}`}><AppIcon name="plus" />Add division</button></form></section>
        </div>
    </aside></div>;
}
