import AppIcon from '@/Components/AppIcon';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';

const field = 'mt-1 w-full rounded-lg border-slate-300 text-sm focus:border-[#0B536D] focus:ring-[#0B536D] disabled:bg-slate-100';
const button = 'inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[#0B536D] px-4 text-sm font-bold text-white disabled:opacity-50';

function SportDrawer({ event, sport, onClose }) {
    const details = useForm({ name: sport.name, slug: sport.slug });
    const division = useForm({ name: '', slug: '' });
    const state = useForm({ active: !sport.active, reason: '' });
    useEffect(() => { const handler = (e) => e.key === 'Escape' && onClose(); document.addEventListener('keydown', handler); return () => document.removeEventListener('keydown', handler); }, [onClose]);
    return <div className="fixed inset-0 z-50"><button aria-label="Close sport editor backdrop" onClick={onClose} className="absolute inset-0 bg-[#17212B]/45"/><aside role="dialog" aria-modal="true" aria-labelledby="sport-drawer-title" className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-[#F4F5F2] shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b border-[#DDE2E0] bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">Sport editor</p><h2 id="sport-drawer-title" className="mt-1 font-serif text-2xl font-bold">{sport.name}</h2></div><button autoFocus onClick={onClose} aria-label="Close sport editor" className="grid size-10 place-items-center rounded-lg focus-visible:ring-2 focus-visible:ring-[#D5A21F]"><AppIcon name="close"/></button></header><div className="space-y-5 p-5">
        <form onSubmit={(e) => { e.preventDefault(); details.patch(route('admin.sports.update', [event.id, sport.id]), { preserveScroll: true }); }} className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Identity</h3><label className="mt-4 block text-xs font-bold uppercase">Name<input disabled={event.archived} value={details.data.name} onChange={(e) => details.setData('name', e.target.value)} className={field}/></label><label className="mt-3 block text-xs font-bold uppercase">Public slug<input disabled={event.archived || sport.has_history} value={details.data.slug} onChange={(e) => details.setData('slug', e.target.value)} className={field}/></label>{sport.has_history ? <p className="mt-2 text-xs text-[#68767E]">Slug locked because contest history exists.</p> : null}<button disabled={event.archived || details.processing} className={`mt-4 ${button}`}><AppIcon name="check"/>Save changes</button></form>
        <form onSubmit={(e) => { e.preventDefault(); state.patch(route('admin.sports.state', [event.id, sport.id]), { preserveScroll: true }); }} className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Availability</h3><p className="mt-2 text-sm text-[#68767E]">Deactivation preserves history and removes this sport from new entries, assignments, schedules, and public directories.</p>{sport.active ? <label className="mt-4 block text-xs font-bold uppercase">Required reason<textarea required value={state.data.reason} onChange={(e) => state.setData('reason', e.target.value)} className={field}/></label> : <p className="mt-3 text-sm text-amber-800">Reason: {sport.deactivation_reason}</p>}<button disabled={event.archived || state.processing} className={`mt-4 ${button} ${sport.active ? '!bg-amber-700' : '!bg-[#16845B]'}`}><AppIcon name={sport.active ? 'pause' : 'play'}/>{sport.active ? 'Deactivate sport' : 'Reactivate sport'}</button></form>
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Divisions</h3><div className="mt-4 space-y-3">{sport.divisions.map((item) => <div key={item.id} className="rounded-lg border border-[#E6EAE8] p-4"><div className="flex justify-between gap-4"><div><strong>{item.name}</strong><p className="mt-1 text-xs text-[#68767E]">{item.format?.replaceAll('_', ' ') ?? 'Format not set'} · {item.participant_mode ?? 'mode not set'} · {item.rule_state}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[0.65rem] font-bold uppercase ${item.active ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-600'}`}>{item.active ? 'Active' : 'Inactive'}</span></div><p className="mt-2 text-xs text-[#68767E]">Roster {item.roster_min ?? '—'}–{item.roster_max ?? '—'} · {item.schedule_published ? 'Schedule published' : 'Schedule not published'}</p>{item.blockers.length ? <p className="mt-2 text-xs text-amber-800">{item.blockers.join(' ')}</p> : null}<div className="mt-3 flex flex-wrap gap-3"><Link className="text-xs font-bold text-[#0B536D] underline" href={route('admin.registrations.index', { event: event.id, competition: sport.id, division: item.id })}>Players & Rosters</Link><Link className="text-xs font-bold text-[#0B536D] underline" href={route('admin.public-programme.index', event.id)}>Schedule</Link></div></div>)}</div>
        <form onSubmit={(e) => { e.preventDefault(); division.post(route('admin.sports.divisions.store', [event.id, sport.id]), { preserveScroll: true, onSuccess: () => division.reset() }); }} className="mt-5 border-t border-[#E6EAE8] pt-4"><label className="text-xs font-bold uppercase">New division<input required disabled={event.archived} value={division.data.name} onChange={(e) => division.setData('name', e.target.value)} className={field}/></label><button disabled={event.archived || division.processing} className={`mt-3 ${button}`}><AppIcon name="plus"/>Add division</button></form></section>
    </div></aside></div>;
}

export default function Index({ event, sports = [] }) {
    const [selected, setSelected] = useState(null); const create = useForm({ name: '', slug: '', division_name: '' }); const { flash, errors } = usePage().props;
    return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">{event.name}</p><h1 className="font-serif text-2xl font-bold">Sports & Events</h1></div>}><Head title="Sports & Events"/><main className="p-4 sm:p-7 lg:p-8"><div className="mx-auto max-w-[96rem] space-y-6">{flash?.status ? <div role="status" className="border-l-4 border-[#16845B] bg-emerald-50 p-4 text-sm">{flash.status}</div> : null}{Object.keys(errors ?? {}).length ? <div role="alert" className="border-l-4 border-rose-600 bg-rose-50 p-4 text-sm">{Object.values(errors).join(' ')}</div> : null}
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-serif text-2xl font-bold">Competition directory</h2><p className="mt-1 text-sm text-[#68767E]">Configure active sports without erasing published history.</p></div><form onSubmit={(e) => { e.preventDefault(); create.post(route('admin.sports.store', event.id), { preserveScroll: true, onSuccess: () => create.reset() }); }} className="grid gap-2 sm:grid-cols-3"><input required aria-label="Sport name" placeholder="Sport name" value={create.data.name} onChange={(e) => create.setData('name', e.target.value)} className={field}/><input required aria-label="First division" placeholder="First division" value={create.data.division_name} onChange={(e) => create.setData('division_name', e.target.value)} className={field}/><button disabled={event.archived || create.processing} className={button}><AppIcon name="plus"/>Create sport</button></form></div>
        {sports.length ? <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{sports.map((sport) => <button key={sport.id} onClick={() => setSelected(sport)} className={`relative overflow-hidden rounded-xl border bg-white p-5 text-left shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D5A21F] ${sport.active ? 'border-[#DDE2E0]' : 'border-slate-300 opacity-75'}`}><span className={`absolute inset-y-0 left-0 w-1 ${sport.active ? 'bg-[#D5A21F]' : 'bg-slate-300'}`}/><div className="flex items-start justify-between gap-4"><div><h3 className="font-serif text-xl font-bold">{sport.name}</h3><p className="mt-1 text-xs text-[#68767E]">{sport.divisions.length} divisions · {sport.counts.entries} entries · {sport.counts.players} players</p></div><span className={`rounded-full px-2 py-1 text-[0.65rem] font-bold uppercase ${sport.active ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-600'}`}>{sport.active ? 'Active' : 'Inactive'}</span></div><dl className="mt-5 grid grid-cols-4 gap-2 border-t border-[#E6EAE8] pt-4 text-center"><div><dt className="text-[0.6rem] uppercase text-[#68767E]">Scheduled</dt><dd className="font-mono font-bold">{sport.counts.scheduled}</dd></div><div><dt className="text-[0.6rem] uppercase text-[#68767E]">Live</dt><dd className="font-mono font-bold">{sport.counts.live}</dd></div><div><dt className="text-[0.6rem] uppercase text-[#68767E]">Complete</dt><dd className="font-mono font-bold">{sport.counts.completed}</dd></div><div><dt className="text-[0.6rem] uppercase text-[#68767E]">Official</dt><dd className="font-mono font-bold">{sport.counts.official}</dd></div></dl></button>)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-serif text-xl font-bold">No sports configured</h2><p className="mt-2 text-sm text-[#68767E]">Create the first sport and division above.</p></div>}
    </div></main>{selected ? <SportDrawer event={event} sport={selected} onClose={() => setSelected(null)}/> : null}</AuthenticatedLayout>;
}
