import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import AppIcon from '@/Components/AppIcon';
import { Head, Link, usePage } from '@inertiajs/react';

const panel = 'rounded-xl border border-[#DDE2E0] bg-white';

function Empty({ title, detail, href, action }) {
    return <div className="rounded-xl border border-dashed border-[#C8D0CD] bg-white p-7"><h3 className="font-serif text-lg font-bold">{title}</h3><p className="mt-2 text-sm text-[#68767E]">{detail}</p>{href ? <Link href={href} className="mt-4 inline-flex text-sm font-bold text-[#0B536D] underline decoration-[#D5A21F] decoration-2 underline-offset-4">{action}</Link> : null}</div>;
}

function CommandBar({ event }) {
    const commands = [
        ['user-plus', 'Create participant', 'Add an athlete and build a roster.', route('admin.registrations.index', event.id)],
        ['badge', 'Add event staff', 'Invite a Judge or Tabulator.', route('admin.accounts.create', event.id)],
        ['clipboard-check', 'Review results', 'Verify contests and final rankings.', route('admin.approvals.index', event.id)],
        ['calendar', 'Schedule activity', 'Set venues and publish times.', route('admin.public-programme.index', event.id)],
    ];
    return <section aria-label="Event commands" className={`${panel} overflow-hidden`}><div className="grid grid-cols-2 divide-x divide-y divide-[#E6EAE8] lg:grid-cols-4 lg:divide-y-0">{commands.map(([icon, label, detail, href]) => <Link key={label} href={href} className="group flex min-h-28 gap-3 p-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#D5A21F] sm:p-5"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-[#EAF1F5] text-[#0B536D] group-hover:bg-[#0B536D] group-hover:text-white"><AppIcon name={icon}/></span><span><strong className="block text-sm">{label}</strong><span className="mt-1 hidden text-xs leading-5 text-[#68767E] sm:block">{detail}</span></span></Link>)}</div></section>;
}

function Summary({ data, event }) {
    const cards = [
        ['Participants', data.participants, `${data.eligible_participants} eligible`, route('admin.registrations.index', event.id)],
        ['Event staff', data.event_staff, `${data.unassigned_staff} unassigned`, route('admin.staff.index', event.id)],
        ['Results review', data.pending_results + data.pending_placements, `${data.pending_results} contests / ${data.pending_placements} placements`, route('admin.approvals.index', event.id)],
        ['Live contests', data.live_contests, `${data.approved_placements} placements official`, null],
    ];
    return <dl className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, detail, href]) => { const content = <><dt className="text-[0.68rem] font-bold uppercase tracking-[0.14em] text-[#68767E]">{label}</dt><dd className="mt-2 font-mono text-3xl font-bold">{value}</dd><p className="mt-1 text-xs text-[#68767E]">{detail}</p></>; return href ? <Link key={label} href={href} className={`${panel} p-5 focus-visible:ring-2 focus-visible:ring-[#D5A21F]`}>{content}</Link> : <div key={label} className={`${panel} p-5`}>{content}</div>; })}</dl>;
}

function WorkerDashboard({ event, workQueue }) {
    return <AuthenticatedLayout header={<h1 className="font-serif text-xl font-bold">My scoring assignments</h1>}><Head title="My scoring assignments"/><main className="p-4 sm:p-7"><div className="mx-auto max-w-5xl"><p className="text-sm text-[#68767E]">{event.name} · access is limited to the assignments below.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{workQueue.length ? workQueue.map((work) => <article key={work.id} className={`${panel} p-5`}><p className="text-xs font-bold uppercase text-[#0B536D]">{work.scope.replaceAll('_', ' ')}</p><h2 className="mt-2 font-serif text-lg font-bold">{work.label}</h2>{work.url ? <Link href={work.url} className="mt-4 inline-flex rounded-lg bg-[#0B536D] px-4 py-2 text-sm font-bold text-white">Open assignment</Link> : null}</article>) : <Empty title="No assignments yet" detail="Your role is active, but an administrator has not assigned a scoring target."/>}</div></div></main></AuthenticatedLayout>;
}

export default function Dashboard({ event, summary = {}, pending_approvals: pending = [], live_contests: live = [], teams = [], work_queue: workQueue = [], capabilities = {}, active_tab: activeTab }) {
    const flash = usePage().props.flash?.status;
    if (event && !capabilities.global_admin) return <WorkerDashboard event={event} workQueue={workQueue}/>;
    return <AuthenticatedLayout header={<div><p className="text-[0.68rem] font-bold uppercase tracking-[0.15em] text-[#0B536D]">Administration</p><h1 className="font-serif text-2xl font-bold">Overview</h1></div>}><Head title="Administration overview"/><main className="min-h-[calc(100vh-4rem)] p-4 sm:p-7 lg:p-8"><div className="mx-auto max-w-[96rem] space-y-6">{flash ? <div role="status" className="border-l-4 border-[#16845B] bg-emerald-50 p-4 text-sm text-emerald-900">{flash}</div> : null}{!event ? <Empty title="Create the first event" detail="Start an event workspace, configure sports, then invite event staff." href={route('admin.events.create')} action="Create event"/> : <>
        <section className={`${panel} border-l-4 border-l-[#D5A21F] p-5 sm:flex sm:items-end sm:justify-between`}><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">{event.state}</p><h2 className="mt-1 font-serif text-3xl font-bold">{event.name}</h2><p className="mt-2 text-sm text-[#68767E]">Live operations, official-result gates, and championship standing at a glance.</p></div><Link href={route('admin.sports.index', event.id)} className="mt-4 inline-flex rounded-lg bg-[#0B536D] px-4 py-2.5 text-sm font-bold text-white sm:mt-0">Manage sports</Link></section>
        <Summary data={summary} event={event}/><CommandBar event={event}/>
        {activeTab === 'tournaments' ? <Empty title="Tournament Desk" detail="Choose a sport to review its divisions, generated draws, and current standings." href={route('admin.sports.index', event.id)} action="Choose a sport"/> : <div className="grid gap-6 xl:grid-cols-2"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Live contests</h2><span className="font-mono text-sm text-[#0B536D]">{live.length}</span></div>{live.length ? <div className={`${panel} divide-y divide-[#E6EAE8]`}>{live.map((contest) => <article key={contest.id} className="border-l-4 border-l-[#D5A21F] p-4"><p className="text-xs font-bold uppercase text-[#0B536D]">{contest.competition} / {contest.division}</p><h3 className="mt-1 font-semibold">{contest.name}</h3><p className="mt-1 font-mono text-xs text-[#68767E]">Live revision {contest.revision}</p></article>)}</div> : <Empty title="No contests are live" detail="Published schedules and assigned tabulators appear here once play starts." href={route('admin.public-programme.index', event.id)} action="Open schedules"/>}</section>
        <section><div className="mb-3 flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Results awaiting review</h2><span className="font-mono text-sm text-[#0B536D]">{pending.length}</span></div>{pending.length ? <div className={`${panel} divide-y divide-[#E6EAE8]`}>{pending.map((item) => <Link key={`${item.kind}-${item.id}`} href={route('admin.approvals.index', event.id)} className="block p-4 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#D5A21F]"><p className="text-xs font-bold uppercase text-[#0B536D]">{item.kind}</p><p className="mt-1 text-sm font-semibold">{item.label}</p></Link>)}</div> : <Empty title="Review queue is clear" detail="Submitted contest results and final placements appear here." href={route('admin.approvals.index', event.id)} action="Open Results Review"/>}</section></div>}
        <section><div className="mb-3 flex items-center justify-between"><h2 className="font-serif text-xl font-bold">Championship standings</h2><span className="text-xs text-[#68767E]">Official ledger only</span></div>{teams.length ? <div className={`${panel} overflow-x-auto`}><table className="w-full text-left text-sm"><thead className="border-b border-[#DDE2E0] bg-[#F8F9F7] text-xs uppercase text-[#68767E]"><tr><th className="px-4 py-3">Rank</th><th>Department</th><th className="px-4 text-right">Points</th></tr></thead><tbody className="divide-y divide-[#E6EAE8]">{teams.map((team, index) => <tr key={team.id}><td className="px-4 py-3 font-mono text-[#68767E]">{index + 1}</td><td><strong>{team.abbreviation}</strong><span className="ml-2 text-xs text-[#68767E]">{team.name}</span></td><td className="px-4 text-right font-mono text-lg font-bold">{team.championship_total}</td></tr>)}</tbody></table></div> : <Empty title="No official standings yet" detail="Standings update only after a final placement writes to the immutable ledger." href={route('admin.approvals.index', event.id)} action="Review placements"/>}</section>
    </>}</div></main></AuthenticatedLayout>;
}
