import AppIcon from '@/Components/AppIcon';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm, usePage } from '@inertiajs/react';

const when = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Time unavailable';
const input = 'min-w-0 flex-1 rounded-lg border-slate-300 text-sm focus:border-[#0B536D] focus:ring-[#0B536D]';

function Outcome({ submission }) {
    const approve = useForm({ reason: '' }); const reject = useForm({ reason: '' });
    return <article className="border-b border-slate-200 bg-white p-5 last:border-b-0 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">Contest result · revision {submission.revision}</p><h3 className="mt-1 font-serif text-lg font-bold">{submission.competition} / {submission.division} / {submission.contest}</h3><p className="mt-2 text-sm text-slate-500">Submitted by {submission.submitted_by ?? 'Unknown'} · {when(submission.submitted_at)}</p></div><span className="h-fit w-fit rounded-full bg-amber-50 px-3 py-1 text-xs font-bold uppercase text-amber-800">Awaiting review</span></div>
        <dl className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-lg bg-slate-200 sm:grid-cols-4">{Object.entries(submission.payload).map(([key, value]) => <div key={key} className="bg-slate-50 p-3"><dt className="text-[0.62rem] uppercase text-slate-500">{key.replaceAll('_', ' ')}</dt><dd className="mt-1 break-words font-mono text-sm font-bold">{typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl>
        <div className="mt-5 grid gap-3 lg:grid-cols-2"><form onSubmit={(e) => { e.preventDefault(); approve.post(route('admin.results.approve', submission.id), { preserveScroll: true }); }} className="flex gap-2"><input aria-label="Approval note" placeholder="Approval note (optional)" value={approve.data.reason} onChange={(e) => approve.setData('reason', e.target.value)} className={input}/><button disabled={approve.processing || reject.processing} className="inline-flex items-center gap-2 rounded-lg bg-[#0B536D] px-4 text-sm font-bold text-white"><AppIcon name="check" className="size-4"/>Approve result</button></form><form onSubmit={(e) => { e.preventDefault(); reject.post(route('admin.results.reject', submission.id), { preserveScroll: true }); }} className="flex gap-2"><input required aria-label="Required correction reason" placeholder="Required correction reason" value={reject.data.reason} onChange={(e) => reject.setData('reason', e.target.value)} className={input}/><button disabled={approve.processing || reject.processing} className="inline-flex items-center gap-2 rounded-lg border border-rose-300 px-4 text-sm font-bold text-rose-800"><AppIcon name="close" className="size-4"/>Reject</button></form></div>
    </article>;
}

function Placement({ placement }) {
    const form = useForm({ reason: '' });
    return <article className="border-b border-slate-200 bg-white p-5 last:border-b-0 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9A7210]">Final ranking · revision {placement.revision}</p><h3 className="mt-1 font-serif text-lg font-bold">{placement.competition} / {placement.division}</h3><p className="mt-2 text-sm text-slate-500">Submitted by {placement.submitted_by ?? 'Unknown'} · {when(placement.submitted_at)}</p></div><span className="h-fit w-fit rounded-full bg-amber-50 px-3 py-1 text-xs font-bold uppercase text-amber-800">Ledger pending</span></div>
        <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase text-slate-500"><tr><th className="py-2">Rank</th><th>Entry</th><th>Delegation</th><th className="text-right">Signed points</th></tr></thead><tbody className="divide-y divide-slate-100">{placement.items.map((item) => <tr key={item.id}><td className="py-3 font-mono font-bold">{item.rank}</td><td>{item.entry}</td><td>{item.delegation}</td><td className="text-right font-mono font-bold">{item.points}</td></tr>)}</tbody></table></div>
        <form onSubmit={(e) => { e.preventDefault(); if (window.confirm('Approve this complete ranking and commit exactly one immutable set of signed championship points?')) form.post(route('admin.placements.approve', placement.id), { preserveScroll: true }); }} className="mt-5 flex flex-col gap-2 sm:flex-row"><input aria-label="Placement approval note" placeholder="Approval note (optional)" value={form.data.reason} onChange={(e) => form.setData('reason', e.target.value)} className={input}/><button disabled={form.processing} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#D5A21F] px-5 text-sm font-bold text-[#17212B]"><AppIcon name="clipboard-check" className="size-4"/>Approve placement and commit points</button></form>
    </article>;
}

export default function Index({ event, result_submissions: submissions = [], division_placements: placements = [] }) {
    const { flash, errors } = usePage().props; const empty = !submissions.length && !placements.length;
    return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">{event.name}</p><h1 className="font-serif text-2xl font-bold">Results Review</h1></div>}><Head title="Results Review"/><main className="min-h-[calc(100vh-4rem)] p-4 sm:p-7 lg:p-8"><div className="mx-auto max-w-6xl space-y-8">{flash?.status ? <div role="status" className="border-l-4 border-[#16845B] bg-emerald-50 p-4 text-sm">{flash.status}</div> : null}{errors?.approval ? <div role="alert" className="border-l-4 border-rose-600 bg-rose-50 p-4 text-sm">{errors.approval}</div> : null}
        <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">Contest results</p><p className="mt-2 font-mono text-4xl font-bold">{submissions.length}</p><p className="mt-2 text-sm text-slate-500">Approval makes a winner and score official. It never awards championship points.</p></div><div className="rounded-xl border border-[#D5A21F] bg-white p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9A7210]">Championship placements</p><p className="mt-2 font-mono text-4xl font-bold">{placements.length}</p><p className="mt-2 text-sm text-slate-500">Approval commits signed points to the immutable championship ledger.</p></div></section>
        {empty ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Nothing is waiting for review. Approved and rejected records remain in audit history.</div> : null}
        {submissions.length ? <section><h2 className="font-serif text-xl font-bold">Contest results</h2><p className="mb-3 mt-1 text-sm text-slate-500">Verify evidence, actor, timestamp, and revision before making the result official.</p><div className="overflow-hidden rounded-xl border border-slate-200">{submissions.map((item) => <Outcome key={item.id} submission={item}/>)}</div></section> : null}
        {placements.length ? <section><h2 className="font-serif text-xl font-bold">Championship placements</h2><p className="mb-3 mt-1 text-sm text-slate-500">Review the complete ranking separately. This is the only gate that creates championship ledger entries.</p><div className="overflow-hidden rounded-xl border border-slate-200">{placements.map((item) => <Placement key={item.id} placement={item}/>)}</div></section> : null}
    </div></main></AuthenticatedLayout>;
}
