import AppIcon from '@/Components/AppIcon';
import React from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Link from '@/Components/PrefetchLink';
import { Head, useForm, usePage } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const control = 'mt-1 w-full rounded-lg border-border bg-surface text-sm text-foreground focus:border-primary focus:ring-primary';
const action = 'inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground disabled:opacity-50';

function StaffDrawer({ event, person, targets, onClose }) {
    const role = useForm({ role: person.roles.some((r) => r.role === 'judge') ? 'tabulator' : 'judge' });
    const assignment = useForm({ scope_type: 'competition_division', target_id: '' });
    const account = useForm({ reason: '' });
    const isJudge = person.roles.some((r) => r.role === 'judge');
    const isTabulator = person.roles.some((r) => r.role === 'tabulator');
    const judgingAssignments = person.judging_assignments ?? person.assignments.filter((item) => item.scope === 'entry_scorecard');
    const tabulatorAssignments = person.tabulator_assignments ?? person.assignments.filter((item) => item.scope !== 'entry_scorecard');
    const options = targets[assignment.data.scope_type] ?? [];
    const reasonAction = (url) => { const reason = window.prompt('Enter the required audit reason:'); if (reason?.trim()) account.transform(() => ({ reason })).patch(url, { preserveScroll: true, onFinish: () => account.reset() }); };
    const assignmentList = (items, empty) => items.length
        ? <div className="mt-3 space-y-2">{items.map((item) => <div key={item.id} className="rounded-xl border border-border bg-surface-muted p-3"><p className="text-[0.65rem] font-bold uppercase tracking-[0.1em] text-primary">{item.scope.replaceAll('_', ' ')}</p><div className="mt-1 flex items-start justify-between gap-3"><span className="text-sm text-foreground">{item.label}</span><button onClick={() => reasonAction(route('admin.staff.assignments.revoke', [event.id, item.id]))} className="text-xs font-bold text-danger">Revoke</button></div></div>)}</div>
        : <p className="mt-2 rounded-xl bg-accent/10 p-3 text-sm text-accent-foreground">{empty}</p>;
    return <div className="fixed inset-0 z-50"><button aria-label="Close staff details backdrop" onClick={onClose} className="absolute inset-0 bg-foreground/45"/><aside role="dialog" aria-modal="true" aria-labelledby="staff-title" className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-background shadow-2xl"><header className="sticky top-0 z-10 flex justify-between border-b border-border bg-surface p-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Staff record</p><h2 id="staff-title" className="mt-1 font-serif text-2xl font-bold">{person.name}</h2><p className="mt-1 text-sm text-muted">{person.email}</p></div><button autoFocus onClick={onClose} aria-label="Close staff details" className="grid size-10 place-items-center rounded-lg focus-visible:ring-2 focus-visible:ring-accent"><AppIcon name="close"/></button></header><div className="space-y-5 p-5">
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><div className="flex flex-wrap items-center gap-2">{person.roles.map((r) => <span key={r.id} className="rounded-full bg-[#EAF1F5] px-3 py-1 text-xs font-bold uppercase text-[#0B536D]">{r.role}</span>)}<span className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${person.account_state === 'active' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`}>{person.account_state}</span></div><p className="mt-4 text-sm text-[#68767E]">Invitation: {person.invitation?.state ?? 'account already established'}{person.invitation?.expires_at ? ` · expires ${new Date(person.invitation.expires_at).toLocaleString()}` : ''}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={event.archived} onClick={() => account.post(route('admin.staff.invitations.reissue', [event.id, person.id]), { preserveScroll: true })} className={action}>Reissue setup link</button>{person.account_state === 'active' ? <button disabled={event.archived} onClick={() => reasonAction(route('admin.staff.disable', [event.id, person.id]))} className={`${action} !bg-rose-700`}>Disable account</button> : <button disabled={event.archived} onClick={() => account.patch(route('admin.staff.enable', [event.id, person.id]), { preserveScroll: true })} className={`${action} !bg-[#16845B]`}>Reactivate account</button>}</div>{person.event_memberships.length > 1 ? <div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900"><strong>Platform-wide effect.</strong> Disabling affects {person.event_memberships.map((m) => m.event).join(', ')}. Reactivation restores access represented by active grants.</div> : null}</section>
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Event roles</h3><div className="mt-3 space-y-2">{person.roles.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border border-[#E6EAE8] p-3"><span className="text-sm font-bold capitalize">{item.role}</span><button onClick={() => reasonAction(route('admin.staff.roles.revoke', [event.id, item.id]))} className="text-xs font-bold text-rose-700">Revoke</button></div>)}</div><form onSubmit={(e) => { e.preventDefault(); role.post(route('admin.staff.roles.store', [event.id, person.id]), { preserveScroll: true }); }} className="mt-4 flex gap-2"><select value={role.data.role} onChange={(e) => role.setData('role', e.target.value)} className={control}><option value="judge">Judge</option><option value="tabulator">Tabulator</option></select><button disabled={event.archived || role.processing} className={action}>Grant role</button></form></section>
        {isJudge ? <section className="rounded-xl border border-border bg-surface p-5"><h3 className="font-serif text-lg font-bold">Judging assignments</h3><p className="mt-1 text-sm text-muted">Assignments are managed through judging panels.</p>{assignmentList(judgingAssignments, 'No scorecards are assigned through a judging panel yet.')}</section> : null}
        {isTabulator ? <section className="rounded-xl border border-border bg-surface p-5"><h3 className="font-serif text-lg font-bold">Tabulator assignments</h3>{assignmentList(tabulatorAssignments, 'No division or contest assignment yet.') }<form onSubmit={(e) => { e.preventDefault(); assignment.post(route('admin.staff.assignments.store', [event.id, person.id]), { preserveScroll: true }); }} className="mt-4 grid gap-2 sm:grid-cols-2"><select aria-label="Tabulator assignment scope" value={assignment.data.scope_type} onChange={(e) => assignment.setData({ scope_type: e.target.value, target_id: '' })} className={control}><option value="competition_division">Competition division</option><option value="contest">Contest</option></select><select required aria-label="Tabulator assignment target" value={assignment.data.target_id} onChange={(e) => assignment.setData('target_id', e.target.value)} className={control}><option value="">Choose target</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><button disabled={event.archived || assignment.processing} className={`${action} sm:col-span-2`}>Add tabulator assignment</button></form></section> : null}
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Audit history</h3>{person.audit.length ? <ol className="mt-3 divide-y divide-[#E6EAE8]">{person.audit.map((item, i) => <li key={`${item.action}-${i}`} className="py-3 text-sm"><strong>{item.action.replaceAll('.', ' ')}</strong><p className="mt-1 text-xs text-[#68767E]">{item.at ? new Date(item.at).toLocaleString() : 'Time unavailable'}{item.reason ? ` · ${item.reason}` : ''}</p></li>)}</ol> : <p className="mt-2 text-sm text-[#68767E]">No relevant audit records yet.</p>}</section>
    </div></aside></div>;
}

function SectionNav({ event, section }) {
    const sections = [['people', 'People'], ['assignments', 'Assignments'], ['readiness', 'Scoring Readiness']];
    return <nav aria-label="Judges and Tabulators sections" className="flex gap-1 overflow-x-auto border-b border-border">{sections.map(([key, label]) => <Link key={key} href={route('admin.staff.index', { event: event.id, section: key })} aria-current={section === key ? 'page' : undefined} className={`min-h-11 shrink-0 border-b-2 px-4 py-3 text-sm font-bold ${section === key ? 'border-primary text-primary' : 'border-transparent text-muted hover:text-foreground'}`}>{label}</Link>)}</nav>;
}

function TieResolutionForm({ tie }) {
    const form = useForm({ tied_entry_ids: tie.entry_ids, authorized_order: tie.entry_ids, reference: '', reason: '' });
    const name = (id) => tie.entries.find((entry) => Number(entry.id) === Number(id))?.name ?? `Entry ${id}`;
    const move = (index, direction) => {
        const order = [...form.data.authorized_order]; const target = index + direction;
        if (target < 0 || target >= order.length) return;
        [order[index], order[target]] = [order[target], order[index]]; form.setData('authorized_order', order);
    };
    return <form onSubmit={(e) => { e.preventDefault(); form.post(tie.action, { preserveScroll: true }); }} className="mt-2 rounded-xl border border-accent bg-accent/10 p-4 lg:col-span-3"><fieldset><legend className="text-xs font-bold uppercase tracking-[0.12em] text-accent-foreground">Authorized finish order</legend><ol className="mt-3 space-y-2">{form.data.authorized_order.map((id, index) => <li key={id} className="flex items-center gap-2 rounded-lg bg-surface p-2"><span className="w-7 font-mono font-bold">{index + 1}</span><span className="flex-1 text-sm font-bold">{name(id)}</span><button type="button" aria-label={`Move ${name(id)} up`} disabled={index === 0} onClick={() => move(index, -1)} className="min-h-9 rounded border border-border px-3 disabled:opacity-30">↑</button><button type="button" aria-label={`Move ${name(id)} down`} disabled={index === form.data.authorized_order.length - 1} onClick={() => move(index, 1)} className="min-h-9 rounded border border-border px-3 disabled:opacity-30">↓</button></li>)}</ol></fieldset><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold uppercase tracking-[0.1em] text-muted">Administrative reference<input required value={form.data.reference} onChange={(e) => form.setData('reference', e.target.value)} className={control}/></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-muted">Reason<input required value={form.data.reason} onChange={(e) => form.setData('reason', e.target.value)} className={control}/></label></div><button disabled={form.processing} className={`${action} mt-3`}>Authorize tie order</button></form>;
}

function ReadinessSteps({ steps = [] }) {
    if (!steps.length) return null;

    return <ol aria-label="Sequential scoring readiness" className="mb-1 grid gap-2 lg:col-span-2 lg:grid-cols-2">
        {steps.map((step, index) => { const complete = ['complete', 'prepared', 'configured', 'confirmed', 'ready', 'assigned', 'locked'].includes(step.state); return <li key={step.key} className="flex gap-3 rounded-lg border border-border bg-background/70 p-3">
            <span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${complete ? 'bg-primary text-primary-foreground' : step.state === 'blocked' ? 'bg-danger-surface text-danger' : 'bg-accent/20 text-foreground'}`}>{complete ? '✓' : index + 1}</span>
            <span className="min-w-0"><span className="block text-sm font-bold">{step.label}</span><span className="mt-0.5 block text-xs text-muted">{step.detail}</span></span>
        </li>; })}
    </ol>;
}

function ReadinessActions({ item }) {
    const simple = useForm({});
    const panel = useForm({ judge_ids: [] });
    const aggregation = useForm({ method: 'average', reference: '', reason: '' });
    const deduction = useForm({ rounding_policy: 'ceiling', reference: '', reason: '' });
    const tabulator = useForm({ user_id: '' });
    const nextAction = ['prepare', 'panel', 'aggregation', 'deduction', 'tabulator', 'lock'].find((key) => item.actions?.[key] && (key !== 'tabulator' || item.actions.tabulator_options?.length));
    const toggleJudge = (id) => panel.setData('judge_ids', panel.data.judge_ids.includes(id) ? panel.data.judge_ids.filter((value) => value !== id) : [...panel.data.judge_ids, id]);
    const post = (form, href) => form.post(href, { preserveScroll: true });
    return <div className="grid gap-3 lg:col-span-3 lg:grid-cols-2">
        {item.schedule?.title || item.schedule?.venue ? <div className="rounded-xl border border-border bg-background/70 p-4 lg:col-span-2"><p className="text-xs font-bold uppercase tracking-[0.1em] text-primary">Schedule</p><p className="mt-1 font-bold">{item.schedule.title ?? 'Scheduled scoring window'}</p><p className="mt-1 text-sm text-muted">{item.schedule.venue?.name ?? 'Venue to be confirmed'}{item.schedule.venue?.location ? ` · ${item.schedule.venue.location}` : ''}</p></div> : null}
        {item.readiness_steps?.length ? <ReadinessSteps steps={item.readiness_steps}/> : null}
        {nextAction === 'prepare' ? <button onClick={() => post(simple, item.actions.prepare)} className={action}>Prepare official judged contest</button> : null}
        {nextAction === 'panel' ? <form onSubmit={(e) => { e.preventDefault(); post(panel, item.actions.panel); }} className="rounded-xl border border-border p-4"><fieldset><legend className="text-xs font-bold uppercase tracking-[0.1em] text-muted">Judging panel</legend><div className="mt-2 flex flex-wrap gap-2">{item.actions.judge_options.map((judge) => <label key={judge.id} className="flex min-h-10 items-center gap-2 rounded-lg border border-border px-3 text-sm"><input type="checkbox" checked={panel.data.judge_ids.includes(judge.id)} onChange={() => toggleJudge(judge.id)} className="rounded border-border text-primary focus:ring-accent"/>{judge.name}</label>)}</div></fieldset><button disabled={!panel.data.judge_ids.length || panel.processing} className={`${action} mt-3`}>Save panel</button></form> : null}
        {nextAction === 'aggregation' ? <form onSubmit={(e) => { e.preventDefault(); post(aggregation, item.actions.aggregation); }} className="rounded-xl border border-border p-4"><h4 className="font-bold">Judge score aggregation</h4><p className="mt-1 text-xs text-muted">The proposal does not specify how panel scores combine. Record committee authority before locking.</p><select aria-label="Aggregation method" value={aggregation.data.method} onChange={(e) => aggregation.setData('method', e.target.value)} className={control}><option value="average">Average</option></select><input required aria-label="Aggregation administrative reference" placeholder="Administrative reference" value={aggregation.data.reference} onChange={(e) => aggregation.setData('reference', e.target.value)} className={control}/><input required aria-label="Aggregation reason" placeholder="Reason" value={aggregation.data.reason} onChange={(e) => aggregation.setData('reason', e.target.value)} className={control}/><button className={`${action} mt-3`}>Confirm method</button></form> : null}
        {nextAction === 'deduction' ? <form onSubmit={(e) => { e.preventDefault(); post(deduction, item.actions.deduction); }} className="rounded-xl border border-accent bg-accent/10 p-4"><h4 className="font-bold">Deduction calculation authority</h4><select aria-label="Partial interval rounding" value={deduction.data.rounding_policy} onChange={(e) => deduction.setData('rounding_policy', e.target.value)} className={control}><option value="ceiling">Count any partial interval</option><option value="floor">Count completed intervals only</option><option value="nearest">Round to nearest interval</option></select><input required aria-label="Deduction administrative reference" placeholder="Administrative reference" value={deduction.data.reference} onChange={(e) => deduction.setData('reference', e.target.value)} className={control}/><input required aria-label="Deduction reason" placeholder="Reason" value={deduction.data.reason} onChange={(e) => deduction.setData('reason', e.target.value)} className={control}/><button className={`${action} mt-3`}>Authorize calculation</button></form> : null}
        {nextAction === 'tabulator' ? <form onSubmit={(e) => { e.preventDefault(); const selected = item.actions.tabulator_options.find((option) => option.id === tabulator.data.user_id); if (selected) post(tabulator, selected.href); }} className="rounded-xl border border-border p-4"><label className="text-xs font-bold uppercase tracking-[0.1em] text-muted">Assigned Tabulator<select required value={tabulator.data.user_id} onChange={(e) => tabulator.setData('user_id', e.target.value)} className={control}><option value="">Choose Tabulator</option>{item.actions.tabulator_options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><button disabled={!tabulator.data.user_id} className={`${action} mt-3`}>Assign Tabulator</button></form> : null}
        {nextAction === 'lock' ? <button onClick={() => post(simple, item.actions.lock)} className={action}>Lock judging panel</button> : null}
    </div>;
}

export default function Index({ event, section = 'people', staff = [], targets = {}, readiness = [] }) {
    const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [selected, setSelected] = useState(null); const { flash, errors } = usePage().props;
    const visible = useMemo(() => staff.filter((p) => (!query || `${p.name} ${p.email}`.toLowerCase().includes(query.toLowerCase())) && (!roleFilter || p.roles.some((r) => r.role === roleFilter))), [staff, query, roleFilter]);
    if (section === 'readiness') return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{event.name}</p><h1 className="font-serif text-2xl font-bold">Judges &amp; Tabulators</h1></div>}><Head title="Scoring Readiness"/><main className="min-h-[calc(100vh-4rem)] bg-background p-4 text-foreground sm:p-7 lg:p-8"><div className="mx-auto max-w-[96rem] space-y-6"><SectionNav event={event} section={section}/><header><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Control room</p><h2 className="mt-1 font-serif text-3xl font-bold">Scoring Readiness</h2><p className="mt-2 text-sm text-muted">Resolve the next named blocker for every judged competition.</p></header><div className="overflow-hidden rounded-xl border border-border bg-surface"><ul className="divide-y divide-border">{readiness.map((item) => <li key={item.id ?? item.name} className="grid gap-4 p-5 lg:grid-cols-[minmax(14rem,1fr)_auto_minmax(18rem,1.2fr)] lg:items-center"><div><h3 className="font-serif text-xl font-bold">{item.name}</h3><p className="mt-1 text-sm text-muted">{item.counts.entries} entries · {item.counts.judges} Judges · {item.counts.tabulators} Tabulators</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold uppercase ${item.state === 'blocked' ? 'bg-danger-surface text-danger' : item.state === 'ready' ? 'bg-primary/10 text-primary' : 'bg-accent/20 text-foreground'}`}>{item.state === 'needs_attention' ? 'Needs attention' : item.state.charAt(0).toUpperCase() + item.state.slice(1)}</span><p className={`text-sm font-semibold ${item.state === 'blocked' ? 'text-danger' : 'text-muted'}`}>{item.next_blocker ?? 'Ready for scoring operations.'}</p><ReadinessActions item={item}/>{item.tie ? <TieResolutionForm tie={item.tie}/> : null}</li>)}</ul></div></div></main></AuthenticatedLayout>;
    return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{event.name}</p><h1 className="font-serif text-2xl font-bold">Judges &amp; Tabulators</h1></div>}><Head title="Judges & Tabulators"/><main className="bg-background p-4 sm:p-7 lg:p-8"><div className="mx-auto max-w-[96rem] space-y-6"><SectionNav event={event} section={section}/>{flash?.status ? <div role="status" className="border-l-4 border-primary bg-primary/10 p-4 text-sm">{flash.status}</div> : null}{flash?.setup_url ? <div className="rounded-xl border border-accent bg-accent/15 p-4"><strong className="text-sm">One-time setup link</strong><div className="mt-2 flex gap-2"><input readOnly value={flash.setup_url} className="min-w-0 flex-1 rounded-lg border-border bg-surface text-sm text-foreground"/><button onClick={() => navigator.clipboard.writeText(flash.setup_url)} className={action}>Copy link</button></div></div> : null}{Object.keys(errors ?? {}).length ? <div role="alert" className="border-l-4 border-danger bg-danger-surface p-4 text-sm text-danger">{Object.values(errors).join(' ')}</div> : null}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-serif text-2xl font-bold">Judges and Tabulators</h2><p className="mt-1 text-sm text-muted">One workspace for invitations, roles, assignments, and platform account state.</p></div><Link href={route('admin.accounts.create', event.id)} className={action}><AppIcon name="user-plus"/>Invite staff</Link></div>
        <div className="grid gap-3 rounded-xl border border-border bg-surface p-4 sm:grid-cols-[1fr_14rem]"><label className="relative"><span className="sr-only">Search staff</span><AppIcon name="search" className="absolute left-3 top-3 size-5 text-muted"/><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or institutional email" className="w-full rounded-lg border-border bg-surface text-foreground pl-10 text-sm"/></label><select aria-label="Filter by role" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)} className="rounded-lg border-border bg-surface text-foreground text-sm"><option value="">All roles</option><option value="judge">Judges</option><option value="tabulator">Tabulators</option></select></div>
        {visible.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((person) => <button key={person.id} onClick={() => setSelected(person)} className="rounded-xl border border-[#DDE2E0] bg-white p-5 text-left shadow-xs focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-[#D5A21F]"><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-serif text-lg font-bold">{person.name}</h3><p className="mt-1 truncate text-xs text-[#68767E]">{person.email}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[0.65rem] font-bold uppercase ${person.account_state === 'active' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`}>{person.account_state}</span></div><div className="mt-4 flex flex-wrap gap-2">{person.roles.map((r) => <span key={r.id} className="rounded-full bg-[#EAF1F5] px-2 py-1 text-[0.65rem] font-bold uppercase text-[#0B536D]">{r.role}</span>)}</div><p className={`mt-4 text-xs ${person.assignments.length ? 'text-[#68767E]' : 'font-bold text-amber-800'}`}>{person.assignments.length ? `${person.assignments.length} active assignments` : 'Unassigned — needs an exact scoring target'}</p></button>)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-[#68767E]">No staff match these filters.</div>}
    </div></main>{selected ? <StaffDrawer event={event} person={selected} targets={targets} onClose={() => setSelected(null)}/> : null}</AuthenticatedLayout>;
}
