import AppIcon from '@/Components/AppIcon';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const control = 'mt-1 w-full rounded-lg border-slate-300 text-sm focus:border-[#0B536D] focus:ring-[#0B536D]';
const action = 'inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[#0B536D] px-4 text-sm font-bold text-white disabled:opacity-50';

function StaffDrawer({ event, person, targets, onClose }) {
    const role = useForm({ role: person.roles.some((r) => r.role === 'judge') ? 'tabulator' : 'judge' });
    const assignment = useForm({ scope_type: 'competition_division', target_id: '' });
    const account = useForm({ reason: '' });
    const options = targets[assignment.data.scope_type] ?? [];
    const reasonAction = (url) => { const reason = window.prompt('Enter the required audit reason:'); if (reason?.trim()) account.transform(() => ({ reason })).patch(url, { preserveScroll: true, onFinish: () => account.reset() }); };
    return <div className="fixed inset-0 z-50"><button aria-label="Close staff details backdrop" onClick={onClose} className="absolute inset-0 bg-[#17212B]/45"/><aside role="dialog" aria-modal="true" aria-labelledby="staff-title" className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto bg-[#F4F5F2] shadow-2xl"><header className="sticky top-0 z-10 flex justify-between border-b border-[#DDE2E0] bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">Staff record</p><h2 id="staff-title" className="mt-1 font-serif text-2xl font-bold">{person.name}</h2><p className="mt-1 text-sm text-[#68767E]">{person.email}</p></div><button autoFocus onClick={onClose} aria-label="Close staff details" className="grid size-10 place-items-center rounded-lg focus-visible:ring-2 focus-visible:ring-[#D5A21F]"><AppIcon name="close"/></button></header><div className="space-y-5 p-5">
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><div className="flex flex-wrap items-center gap-2">{person.roles.map((r) => <span key={r.id} className="rounded-full bg-[#EAF1F5] px-3 py-1 text-xs font-bold uppercase text-[#0B536D]">{r.role}</span>)}<span className={`rounded-full px-3 py-1 text-xs font-bold uppercase ${person.account_state === 'active' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`}>{person.account_state}</span></div><p className="mt-4 text-sm text-[#68767E]">Invitation: {person.invitation?.state ?? 'account already established'}{person.invitation?.expires_at ? ` · expires ${new Date(person.invitation.expires_at).toLocaleString()}` : ''}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={event.archived} onClick={() => account.post(route('admin.staff.invitations.reissue', [event.id, person.id]), { preserveScroll: true })} className={action}>Reissue setup link</button>{person.account_state === 'active' ? <button disabled={event.archived} onClick={() => reasonAction(route('admin.staff.disable', [event.id, person.id]))} className={`${action} !bg-rose-700`}>Disable account</button> : <button disabled={event.archived} onClick={() => account.patch(route('admin.staff.enable', [event.id, person.id]), { preserveScroll: true })} className={`${action} !bg-[#16845B]`}>Reactivate account</button>}</div>{person.event_memberships.length > 1 ? <div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900"><strong>Platform-wide effect.</strong> Disabling affects {person.event_memberships.map((m) => m.event).join(', ')}. Reactivation restores access represented by active grants.</div> : null}</section>
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Event roles</h3><div className="mt-3 space-y-2">{person.roles.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border border-[#E6EAE8] p-3"><span className="text-sm font-bold capitalize">{item.role}</span><button onClick={() => reasonAction(route('admin.staff.roles.revoke', [event.id, item.id]))} className="text-xs font-bold text-rose-700">Revoke</button></div>)}</div><form onSubmit={(e) => { e.preventDefault(); role.post(route('admin.staff.roles.store', [event.id, person.id]), { preserveScroll: true }); }} className="mt-4 flex gap-2"><select value={role.data.role} onChange={(e) => role.setData('role', e.target.value)} className={control}><option value="judge">Judge</option><option value="tabulator">Tabulator</option></select><button disabled={event.archived || role.processing} className={action}>Grant role</button></form></section>
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Assignments</h3>{person.assignments.length ? <div className="mt-3 space-y-2">{person.assignments.map((item) => <div key={item.id} className="rounded-lg border border-[#E6EAE8] p-3"><p className="text-[0.65rem] font-bold uppercase text-[#0B536D]">{item.scope.replaceAll('_', ' ')}</p><div className="mt-1 flex items-start justify-between gap-3"><span className="text-sm">{item.label}</span><button onClick={() => reasonAction(route('admin.staff.assignments.revoke', [event.id, item.id]))} className="text-xs font-bold text-rose-700">Revoke</button></div></div>)}</div> : <p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Unassigned. Add an exact scoring target below.</p>}<form onSubmit={(e) => { e.preventDefault(); assignment.post(route('admin.staff.assignments.store', [event.id, person.id]), { preserveScroll: true }); }} className="mt-4 grid gap-2 sm:grid-cols-2"><select value={assignment.data.scope_type} onChange={(e) => assignment.setData({ scope_type: e.target.value, target_id: '' })} className={control}><option value="competition_division">Competition division</option><option value="contest">Contest</option><option value="entry_scorecard">Scorecard</option></select><select required value={assignment.data.target_id} onChange={(e) => assignment.setData('target_id', e.target.value)} className={control}><option value="">Choose target</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><button disabled={event.archived || assignment.processing} className={`${action} sm:col-span-2`}>Add assignment</button></form></section>
        <section className="rounded-xl border border-[#DDE2E0] bg-white p-5"><h3 className="font-serif text-lg font-bold">Audit history</h3>{person.audit.length ? <ol className="mt-3 divide-y divide-[#E6EAE8]">{person.audit.map((item, i) => <li key={`${item.action}-${i}`} className="py-3 text-sm"><strong>{item.action.replaceAll('.', ' ')}</strong><p className="mt-1 text-xs text-[#68767E]">{item.at ? new Date(item.at).toLocaleString() : 'Time unavailable'}{item.reason ? ` · ${item.reason}` : ''}</p></li>)}</ol> : <p className="mt-2 text-sm text-[#68767E]">No relevant audit records yet.</p>}</section>
    </div></aside></div>;
}

export default function Index({ event, staff = [], targets = {} }) {
    const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [selected, setSelected] = useState(null); const { flash, errors } = usePage().props;
    const visible = useMemo(() => staff.filter((p) => (!query || `${p.name} ${p.email}`.toLowerCase().includes(query.toLowerCase())) && (!roleFilter || p.roles.some((r) => r.role === roleFilter))), [staff, query, roleFilter]);
    return <AuthenticatedLayout header={<div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0B536D]">{event.name}</p><h1 className="font-serif text-2xl font-bold">Event Staff</h1></div>}><Head title="Event Staff"/><main className="p-4 sm:p-7 lg:p-8"><div className="mx-auto max-w-[96rem] space-y-6">{flash?.status ? <div role="status" className="border-l-4 border-[#16845B] bg-emerald-50 p-4 text-sm">{flash.status}</div> : null}{flash?.setup_url ? <div className="rounded-xl border border-[#D5A21F] bg-amber-50 p-4"><strong className="text-sm">One-time setup link</strong><div className="mt-2 flex gap-2"><input readOnly value={flash.setup_url} className="min-w-0 flex-1 rounded-lg border-amber-200 text-sm"/><button onClick={() => navigator.clipboard.writeText(flash.setup_url)} className={action}>Copy link</button></div></div> : null}{Object.keys(errors ?? {}).length ? <div role="alert" className="border-l-4 border-rose-600 bg-rose-50 p-4 text-sm">{Object.values(errors).join(' ')}</div> : null}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-serif text-2xl font-bold">Judges and Tabulators</h2><p className="mt-1 text-sm text-[#68767E]">One workspace for invitations, roles, assignments, and platform account state.</p></div><Link href={route('admin.accounts.create', event.id)} className={action}><AppIcon name="user-plus"/>Invite staff</Link></div>
        <div className="grid gap-3 rounded-xl border border-[#DDE2E0] bg-white p-4 sm:grid-cols-[1fr_14rem]"><label className="relative"><span className="sr-only">Search staff</span><AppIcon name="search" className="absolute left-3 top-3 size-5 text-[#68767E]"/><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or institutional email" className="w-full rounded-lg border-slate-300 pl-10 text-sm"/></label><select aria-label="Filter by role" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)} className="rounded-lg border-slate-300 text-sm"><option value="">All roles</option><option value="judge">Judges</option><option value="tabulator">Tabulators</option></select></div>
        {visible.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((person) => <button key={person.id} onClick={() => setSelected(person)} className="rounded-xl border border-[#DDE2E0] bg-white p-5 text-left shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D5A21F]"><div className="flex justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-serif text-lg font-bold">{person.name}</h3><p className="mt-1 truncate text-xs text-[#68767E]">{person.email}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[0.65rem] font-bold uppercase ${person.account_state === 'active' ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`}>{person.account_state}</span></div><div className="mt-4 flex flex-wrap gap-2">{person.roles.map((r) => <span key={r.id} className="rounded-full bg-[#EAF1F5] px-2 py-1 text-[0.65rem] font-bold uppercase text-[#0B536D]">{r.role}</span>)}</div><p className={`mt-4 text-xs ${person.assignments.length ? 'text-[#68767E]' : 'font-bold text-amber-800'}`}>{person.assignments.length ? `${person.assignments.length} active assignments` : 'Unassigned — needs an exact scoring target'}</p></button>)}</div> : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-[#68767E]">No staff match these filters.</div>}
    </div></main>{selected ? <StaffDrawer event={event} person={selected} targets={targets} onClose={() => setSelected(null)}/> : null}</AuthenticatedLayout>;
}
